apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetstore-pv-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# Check it by running kubectl describe pvc